#!/usr/bin/env python3
"""
Sync Google Sheet → Obsidian vault mission notes.

Reads mission data + pilot assignments from the Pilot Planner Sheet,
then updates YAML frontmatter and assignment sections in vault notes.

Usage: python3 sync_sheet_to_obsidian.py [--dry-run]
"""

import os, re, json, sys, urllib.request
from datetime import datetime

# === CONFIG ===
VAULT_MISSIONS = "/Users/willy/Library/Mobile Documents/com~apple~CloudDocs/THC Vault/THC/Missions"
APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbx2PG54ptMJw3eJW2vxNrvRJOaJVfXzOQYnJg-qHbV0vrBU1W16tq2lpGKlVfVXVpyX6w/exec"
DRY_RUN = "--dry-run" in sys.argv

# Fields to sync FROM Sheet TO Obsidian (Sheet key → frontmatter key)
SYNC_FIELDS = {
    'Status': 'status',
    'Start': 'date',
    'End': 'endDate',
}


def fetch_sheet_data():
    """Fetch all data from the Sheet."""
    url = f"{APPS_SCRIPT_URL}?action=readAll"
    req = urllib.request.Request(url)
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read())


def parse_date(iso_str):
    """Extract YYYY-MM-DD from ISO timestamp."""
    if not iso_str:
        return None
    return iso_str[:10]


def update_frontmatter_field(fm_text, key, value):
    """Update a single field in YAML frontmatter text. Returns modified text."""
    pattern = rf'^({re.escape(key)}:\s*)(.*)$'
    match = re.search(pattern, fm_text, re.MULTILINE)
    if match:
        return re.sub(pattern, rf'\g<1>{value}', fm_text, flags=re.MULTILINE)
    else:
        # Add field before the closing ---
        return fm_text + f'{key}: {value}\n'


def update_helicopter_fields(fm_text, heli_details_json):
    """Update helicopter fields in frontmatter from Sheet's HelicopterDetails JSON."""
    if not heli_details_json:
        return fm_text
    
    try:
        helis = json.loads(heli_details_json)
    except (json.JSONDecodeError, TypeError):
        return fm_text
    
    if not helis:
        return fm_text
    
    # Update helicopter_count
    fm_text = update_frontmatter_field(fm_text, 'helicopter_count', str(len(helis)))
    
    # Remove all existing heli_N_* fields
    fm_text = re.sub(r'^heli_\d+_\w+:.*\n', '', fm_text, flags=re.MULTILINE)
    
    # Add new helicopter fields before the closing line
    heli_lines = []
    for i, h in enumerate(helis, 1):
        heli_lines.append(f"heli_{i}_reg: {h.get('reg', 'TBD')}")
        if h.get('role'):
            heli_lines.append(f"heli_{i}_role: {h['role']}")
        if h.get('start'):
            heli_lines.append(f"heli_{i}_start: {h['start']}")
        if h.get('end'):
            heli_lines.append(f"heli_{i}_end: {h['end']}")
    
    # Insert after helicopter_count line
    count_match = re.search(r'^helicopter_count:.*$', fm_text, re.MULTILINE)
    if count_match:
        insert_pos = count_match.end()
        fm_text = fm_text[:insert_pos] + '\n' + '\n'.join(heli_lines) + fm_text[insert_pos:]
    else:
        fm_text += '\n'.join(heli_lines) + '\n'
    
    return fm_text


def build_assignment_section(assignments):
    """Build a markdown section for pilot assignments from Sheet data."""
    if not assignments:
        return None
    
    # Group by week
    weekly = {}
    for a in sorted(assignments, key=lambda x: x.get('Start', '')):
        start = parse_date(a.get('Start', ''))
        end = parse_date(a.get('End', ''))
        pilot = a.get('Pilot', 'Unknown')
        heli = a.get('HeliSlot', '')
        key = f"{start} → {end}"
        if key not in weekly:
            weekly[key] = []
        weekly[key].append(f"{pilot} ({heli})")
    
    lines = ["#### Pilot Assignments (from Planner) ####"]
    lines.append("<!-- AUTO-GENERATED by sync_sheet_to_obsidian.py — do not edit manually -->")
    lines.append("")
    lines.append("| Week | Pilots |")
    lines.append("|------|--------|")
    for week, pilots in weekly.items():
        lines.append(f"| {week} | {', '.join(pilots)} |")
    lines.append("")
    
    return '\n'.join(lines)


def update_assignment_section(note_text, new_section):
    """Replace or append the auto-generated assignment section in a note."""
    marker_start = "#### Pilot Assignments (from Planner) ####"
    marker_comment = "<!-- AUTO-GENERATED by sync_sheet_to_obsidian.py"
    
    # Find existing auto-generated section
    pattern = r'#### Pilot Assignments \(from Planner\) ####\n<!-- AUTO-GENERATED.*?(?=\n####|\n---|\Z)'
    match = re.search(pattern, note_text, re.DOTALL)
    
    if match:
        return note_text[:match.start()] + new_section + note_text[match.end():]
    else:
        # Append at end
        return note_text.rstrip() + '\n\n' + new_section + '\n'


def sync_mission(mission, assignments, dry_run=False):
    """Sync a single mission from Sheet → Obsidian note."""
    obsidian_file = mission.get('ObsidianFile', '')
    if not obsidian_file:
        return False
    
    filepath = os.path.join(VAULT_MISSIONS, obsidian_file)
    if not os.path.exists(filepath):
        print(f"  ⚠️  File not found: {obsidian_file}")
        return False
    
    text = open(filepath, 'r').read()
    fm_match = re.search(r'^(---\n)(.*?)(\n---)', text, re.DOTALL)
    if not fm_match:
        print(f"  ⚠️  No frontmatter: {obsidian_file}")
        return False
    
    original_text = text
    fm = fm_match.group(2)
    changes = []
    
    # Sync status
    sheet_status = mission.get('Status', '').lower()
    vault_status = None
    m = re.search(r'^status:\s*(.*)$', fm, re.MULTILINE)
    if m:
        vault_status = m.group(1).strip().lower()
    
    if sheet_status and sheet_status != vault_status:
        fm = update_frontmatter_field(fm, 'status', sheet_status)
        changes.append(f"status: {vault_status} → {sheet_status}")
    
    # Sync dates
    sheet_start = parse_date(mission.get('Start', ''))
    sheet_end = parse_date(mission.get('End', ''))
    
    vault_start = None
    m = re.search(r'^date:\s*(.*)$', fm, re.MULTILINE)
    if m:
        vault_start = m.group(1).strip()
    
    vault_end = None
    m = re.search(r'^endDate:\s*(.*)$', fm, re.MULTILINE)
    if m:
        vault_end = m.group(1).strip()
    
    if sheet_start and sheet_start != vault_start:
        fm = update_frontmatter_field(fm, 'date', sheet_start)
        changes.append(f"date: {vault_start} → {sheet_start}")
    
    if sheet_end and sheet_end != vault_end:
        fm = update_frontmatter_field(fm, 'endDate', sheet_end)
        changes.append(f"endDate: {vault_end} → {sheet_end}")
    
    # Sync helicopter details (from the extra column)
    heli_json = mission.get('', '')  # The unnamed column with helicopter JSON
    if heli_json:
        old_fm = fm
        fm = update_helicopter_fields(fm, heli_json)
        if fm != old_fm:
            changes.append("helicopters updated")
    
    # Update last_updated timestamp
    timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M+03:00")
    fm = update_frontmatter_field(fm, 'last_updated', timestamp)
    
    # Reconstruct the file with updated frontmatter
    text = fm_match.group(1) + fm + fm_match.group(3) + text[fm_match.end():]
    
    # Update assignment section if there are assignments
    mission_assignments = [a for a in assignments if a.get('MissionID') == mission.get('MissionID')]
    if mission_assignments:
        section = build_assignment_section(mission_assignments)
        text = update_assignment_section(text, section)
        changes.append(f"{len(mission_assignments)} assignments")
    
    if text == original_text:
        return False
    
    if dry_run:
        print(f"  📝 Would update {obsidian_file}: {', '.join(changes)}")
    else:
        with open(filepath, 'w') as f:
            f.write(text)
        print(f"  ✅ Updated {obsidian_file}: {', '.join(changes)}")
    
    return True


def main():
    print("🔄 Syncing Google Sheet → Obsidian vault")
    print(f"   Vault: {VAULT_MISSIONS}")
    print(f"   Dry run: {DRY_RUN}\n")
    
    data = fetch_sheet_data()
    missions = data.get('missions', [])
    assignments = data.get('assignments', [])
    
    print(f"📊 Sheet: {len(missions)} missions, {len(assignments)} assignments\n")
    
    updated = 0
    for mission in missions:
        mid = mission.get('MissionID', '?')
        name = mission.get('Name', '?')
        result = sync_mission(mission, assignments, DRY_RUN)
        if result:
            updated += 1
        else:
            print(f"  — {mid}: no changes")
    
    print(f"\n{'🏁 Dry run' if DRY_RUN else '✅ Done'}: {updated}/{len(missions)} missions updated")


if __name__ == "__main__":
    main()
